id: gkeclusterclass
title: GKEClusterClass
titlePlural: GKEClusterClasses
category: Compute
overviewShort: "A GKEClusterClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource."
overview: |
 "A GKEClusterClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource."
readme: |
 Full documentation can be found in the Crossplane [API Reference docs](https://doc.crds.dev/github.com/crossplane/provider-gcp/config/crd/compute.gcp.crossplane.io_gkeclusterclasses.yaml@v0.10.0).
