id: gkeclusterclass
title: GKEClusterClass
titlePlural: GKEClusterClasses
category: Container
overviewShort: "A GKEClusterClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource."
overview: |
 "A GKEClusterClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource."
readme: |
 Full documentation can be found in the Crossplane [API Reference docs](https://crossplane.io/docs/master/api/crossplane/stack-gcp/compute-gcp-crossplane-io-v1alpha3.html#GKEClusterClass).
